### ISSUE TITLE
Why is the code for gin and macaron longer than those for Negroni and Martini

### ISSUE THREAD

**Issue by Immortalin** [xyproto/permissionbolt#1]
Out of curiosity, why is the middleware code for gin and macaron longer than those for Negroni and Martini?

**Comment by xyproto** [comment]
Hi,

It's mainly because Gin and Macaron makes use of `*gin.Context` and `*macaron.Context` when handling requests. Modifying `permissionbolt` to provide the appropriate middleware functions would require to introduce a dependency on both gin and macaron. Negroni on the other hand, only uses the standard http functions, so providing middleware for it does not require to depend on negroni.

If there was a generic way to provide middleware handlers to web frameworks that used their own particular `Context` type, I would be happy to use it.

Best regards,
Alexander Rødseth

**Comment by Immortalin** [comment]
Thanks for the explanation!
